site_name: passbook Docs
site_url: https://beryju.github.io/passbook
copyright: "Copyright &copy; 2019 - 2020 BeryJu.org"

nav:
  - Home: index.md
  - Installation:
    - docker-compose: installation/docker-compose.md
    - Kubernetes: installation/kubernetes.md
  - Flows: flow/flows.md
  - Stages:
      - Captcha Stage: flow/stages/captcha/captcha.md
      - Dummy Stage: flow/stages/dummy/dummy.md
      - E-Mail Stage: flow/stages/email/email.md
      - Identification Stage: flow/stages/identification/identification.md
      - Invitation Stage: flow/stages/invitation/invitation.md
      - OTP Stage: flow/stages/otp/otp.md
      - Password Stage: flow/stages/password/password.md
      - Prompt Stage: flow/stages/prompt/prompt.md
      - Prompt Stage Validation: flow/stages/prompt/validation.md
      - User Delete Stage: flow/stages/user_delete.md
      - User Login Stage: flow/stages/user_login.md
      - User Logout Stage: flow/stages/user_logout.md
      - User Write Stage: flow/stages/user_write.md
  - Sources: sources.md
  - Providers: providers.md
  - Property Mappings:
    - Overview: property-mappings/index.md
    - Reference:
      - User Object: property-mappings/reference/user-object.md
  - Policies:
    - Overview: policies/index.md
    - Expression: policies/expression/index.md
  - Integrations:
    - as Provider:
        - Amazon Web Services: integrations/services/aws/index.md
        - GitLab: integrations/services/gitlab/index.md
        - Rancher: integrations/services/rancher/index.md
        - Harbor: integrations/services/harbor/index.md
        - Sentry: integrations/services/sentry/index.md
        - Ansible Tower/AWX: integrations/services/tower-awx/index.md
  - Upgrading from v0.8.x: upgrading-from-0.8.x.md

repo_name: "BeryJu/passbook"
repo_url: https://github.com/BeryJu/passbook
theme:
  name: "material"
  logo: "images/logo.svg"

markdown_extensions:
  - toc:
      permalink: "¶"
  - admonition
