{{- if .Values.kubernetesIntegration }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "passbook.fullname" . }}-sa-role
rules:
- apiGroups:
    - ""
  resources:
    - secrets
    - services
  verbs:
    - "get"
    - "create"
    - "delete"
    - "read"
    - "patch"
- apiGroups:
    - "extensions"
    - "apps"
  resources:
    - "deployments"
  verbs:
    - "get"
    - "create"
    - "delete"
    - "read"
    - "patch"
- apiGroups:
    - "extensions"
    - "networking"
  resources:
    - "ingress"
  verbs:
    - "get"
    - "create"
    - "delete"
    - "read"
    - "patch"
- apiGroups:
    - ""
  resources:
    - namespaces
  verbs:
    - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "passbook.fullname" . }}-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "passbook.fullname" . }}-sa-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "passbook.fullname" . }}-sa-role
subjects:
- kind: ServiceAccount
  name: {{ include "passbook.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
{{- end }}
