dependencies:
- name: postgresql
  version: 4.2.2
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: redis
  version: 9.2.1
  repository: https://kubernetes-charts.storage.googleapis.com/
