version: '3.7'

services:
  hub:
    image: dosel/zalenium
    command: start
    ports:
      - 4444:4444
    environment:
      PULL_SELENIUM_IMAGE: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/videos:/home/seluser/videos
    privileged: true
