# Global Variables
before_script:
  - cd allauth/
  - "python3 -m pip install -U virtualenv"
  - "virtualenv env"
  - "source env/bin/activate"
  - "pip3 install -U -r requirements-dev.txt"
stages:
  - test-allauth
image: python:3.6

isort:
  script:
    - isort -c -sg env
  stage: test-allauth
prospector:
  script:
    - prospector
  stage: test-allauth
pylint:
  script:
    - pylint passbook
  stage: test-allauth
bandit:
  script:
    - bandit -r allauth_passbook
  stage: test-allauth
