trigger:
  batch: true
  branches:
    include:
      - master
      - next
      - version-*

stages:
  - stage: lint
    jobs:
      - job: eslint
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
            displayName: 'Install Node.js'
          - task: Npm@1
            inputs:
              command: 'install'
              workingDir: 'web/'
          - task: CmdLine@2
            inputs:
              script: make gen-web
          - task: Npm@1
            inputs:
              command: 'custom'
              workingDir: 'web/'
              customCommand: 'run lint'
      - job: prettier
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
            displayName: 'Install Node.js'
          - task: Npm@1
            inputs:
              command: 'install'
              workingDir: 'web/'
          - task: CmdLine@2
            inputs:
              script: make gen-web
          - task: Npm@1
            inputs:
              command: 'custom'
              workingDir: 'web/'
              customCommand: 'run prettier-check'
      - job: lit_analyse
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
            displayName: 'Install Node.js'
          - task: Npm@1
            inputs:
              command: 'install'
              workingDir: 'web/'
          - task: CmdLine@2
            inputs:
              script: make gen-web
          - task: Npm@1
            inputs:
              command: 'custom'
              workingDir: 'web/'
              customCommand: 'run lit-analyse'
  - stage: build_local
    jobs:
      - job: build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
            displayName: 'Install Node.js'
          - task: Npm@1
            inputs:
              command: 'install'
              workingDir: 'web/'
          - task: CmdLine@2
            inputs:
              script: make gen-web
          - task: Npm@1
            inputs:
              command: 'custom'
              workingDir: 'web/'
              customCommand: 'run build'
